# Generated by Django 4.0.5 on 2022-06-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dish', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=255)),
            ],
        ),
    ]
