# Generated by Django 4.0.5 on 2022-06-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='name_of_dish',
            new_name='dish_name',
        ),
    ]
